### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pczerkas** [cfpb/xtdiff#1]
Hello,
xtdiff.diff(etree.fromstring("<root><a>10</a></root>"), etree.fromstring("<root><a>1</a><a>10</a></root>"))
raises "IndexError: list index out of range"

**Comment by acrewdson** [comment]
@pczerkas I don't know much about `xtdiff`, but looking at your comment there, it seems like those strings would not be well-formed xml documents:

```
>>> import lxml.etree
>>> lxml.etree.fromstring("10")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1757, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1067, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 639, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

Do you think that might be the problem you're running into here?

**Comment by pczerkas** [comment]
@acrewdson, sorry - I forgot to quote the code properly:
```
>>> xtdiff.diff(etree.fromstring("<root><a><b>10</b></a></root>"), etree.fromstring("<root><a></a><b>110</b></root>"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/przemek/.virtualenvs/rzonca/local/lib/python2.7/site-packages/xtdiff/diff.py", line 513, in diff
    edit_script = editscript(left_tree, right_tree, matches)
  File "/home/przemek/.virtualenvs/rzonca/local/lib/python2.7/site-packages/xtdiff/diff.py", line 380, in editscript
    transform(left_root, set([action, ]))
  File "/home/przemek/.virtualenvs/rzonca/local/lib/python2.7/site-packages/xtdiff/diff.py", line 471, in transform
    node = tree.xpath(action.path)[0]
IndexError: list index out of range
```
